### ISSUE TITLE
Which UDP proxy I can use with go-mmproxy?

### ISSUE THREAD

**Issue by catalystsitaly** [path-network/go-mmproxy#1]
Hi, 
So when using tcp, I can combine HAproxy with mmproxy to forward client IP to service.
Since go-mmproxy supports UDP using proxy protocol v2, but which UDP proxy I can use(haproxy only support tcp) ?

Thanks!

**Comment by kzemek** [comment]
Hi! Sorry for the response delay, I didn't have notifications enabled for the repository (I was pretty sure they were on by default for an author).

Unfortunately I don't know of proxy software that would support UDP proxy protocol. I have modified NGINX source code before to add it, but it's not in a state where upstream would merge it (and I cannot share it at this moment).

Right now I would look at [Envoy](https://github.com/envoyproxy/envoy) as a basis of such a proxy. Its pluggable filters system should make it very easy to add proxy protocol support.

**Comment by christianbur** [comment]
for dns (udp/53) you can use dnsdist.

https://blog.powerdns.com/2020/03/20/first-alpha-release-of-dnsdist-1-5-0/
