### ISSUE TITLE
Too many open files issue cause service down

### ISSUE THREAD

**Issue by jackylam0812** [path-network/go-mmproxy#10]
Hello,

I am facing a problem of "too many open files", error as below :
{"level":"error","ts":1628874839.4984121,"caller":"go-mmproxy/tcp.go:137","msg":"failed to accept new connection","listenerNum":0,"
protocol":"tcp","listenAdr":"0.0.0.0:8085","error":"accept tcp [::]:8085: accept4: too many open files","stacktrace":"main.TCPListen\n\t/root/go/src/github.com/path-ne
twork/go-mmproxy/tcp.go:137\nmain.listen\n\t/root/go/src/github.com/path-network/go-mmproxy/main.go:69"}

the "open files " already set to 409600

core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31193
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 409600
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 409600
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Would anybody help to check how to solve this issue?

**Comment by woodenate** [comment]
If you use Systemd to start go-mmproxy. Use `LimitNOFILE` to set open files.

See also [go-mmproxy.service.example](https://github.com/path-network/go-mmproxy/blob/bda5ebe538cd6d04a10bb289d8c8d4edf9a55611/go-mmproxy.service.example#L7)
