### ISSUE TITLE
"error":"PROXY header missing"

### ISSUE THREAD

**Issue by rezq2009** [path-network/go-mmproxy#16]
Every time I get an error : PROXY header missing
I use Nginx as a proxy & cloudflare .. same issue 

Any idea about this?

**Comment by kzemek** [comment]
Hey @rezq2009 , what is your nginx config?

**Comment by rezq2009** [comment]
Hi @kzemek 


`# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80;
        listen       [::]:80;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        #include /etc/nginx/default.d/*.conf;
		location / {
  proxy_pass              http://168.119.169.150:8443/;
  proxy_set_header        X-Forwarded-For $remote_addr;
  proxy_set_header        Client IP $remote_addr;
  proxy_set_header        CF-Connecting-IP $remote_addr;
  proxy_set_header        True-Client-IP $remote_addr;
  proxy_set_header        Host  $host;
  proxy_pass_request_headers      on;
}


        error_page 404 /404.html;
        location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }
    }

# Settings for a TLS enabled server.
#
#    server {
#        listen       443 ssl http2;
#        listen       [::]:443 ssl http2;
#        server_name  _;
#        root         /usr/share/nginx/html;
#
#        ssl_certificate "/etc/pki/nginx/server.crt";
#        ssl_certificate_key "/etc/pki/nginx/private/server.key";
#        ssl_session_cache shared:SSL:1m;
#        ssl_session_timeout  10m;
#        ssl_ciphers HIGH:!aNULL:!MD5;
#        ssl_prefer_server_ciphers on;
#
#        # Load configuration files for the default server block.
#        include /etc/nginx/default.d/*.conf;
#
#        error_page 404 /404.html;
#            location = /40x.html {
#        }
#
#        error_page 500 502 503 504 /50x.html;
#            location = /50x.html {
#        }
#    }

}

`


and i test with  haproxy same issue

`global
    maxconn 100000
    uid 99
    gid 99
    daemon

defaults
    option forwardfor except 127.0.0.1
    mode    http
    contimeout  5000
    clitimeout  50000
    srvtimeout  50000

listen  myWeb 0.0.0.0:8080
    mode http
    balance source
    option forwardfor
    option http-server-close
    stats enable
    stats refresh 10s
    stats hide-version
    stats scope   .
    stats uri     /lb?stats
    stats realm   LB2\ Statistics
    stats auth admin:passwd

    server  S1 168.119.169.150:8443 check inter 2000 fall 3
    server  S2 168.119.169.150:8443 check inter 2000 fall 3`


i have test with cloudflare to smae issue

debug console message i got 
`
{"level":"debug","ts":1667224570.5431285,"caller":"go-mmproxy@v0.0.0-20220805111550-7197f99c984e/tcp.go:31","msg":"new connection","listenerNum":0,"protocol":"tcp","listenAdr":"0.0.0.0:8443","remoteAddr":"95.216.157.206:52778","localAddr":"168.119.169.150:8443"}
{"level":"debug","ts":1667224570.5432172,"caller":"go-mmproxy@v0.0.0-20220805111550-7197f99c984e/tcp.go:49","msg":"failed to parse PROXY header","listenerNum":0,"protocol":"tcp","listenAdr":"0.0.0.0:8443","remoteAddr":"95.216.157.206:52778","localAddr":"168.119.169.150:8443","error":"PROXY header missing","dropConnection":true}
`

**Comment by kzemek** [comment]
I don't see anything in your nginx config enabling proxy protocol. I don't believe there's a directive to enable it for HTTP servers, only for `stream`s: https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_protocol

For haproxy you need to add `send-proxy` to server options https://cbonte.github.io/haproxy-dconv/2.6/configuration.html#5.2-send-proxy

**Comment by rezq2009** [comment]
@kzemek  Oh, you are right, I forgot about this configuration !!

Thank you very much for your tip
