### ISSUE TITLE
support minecraft server?

### ISSUE THREAD

**Issue by lootoos** [path-network/go-mmproxy#18]
I have launched mmproxy with the following parameters: ./go-mmproxy -l 10.228.228.2:25565
the game server is running on 192.168.0.215, 10.228.228.2 is the ip wireguard
10.228.228.1 is on vds
10.228.228.2 on home pc.
how do I configure mmproxy to log in to a server with the proxy-protocol function enabled in nginx?
home pc: 
![207704911-6a4ff728-817d-4b6f-8380-badd81eed3d1](https://user-images.githubusercontent.com/109325265/207722740-22709361-21e7-44a8-b3f7-10179ba028d5.png)
![207705132-cc6c10a2-6dd4-4cd9-a461-5a7f60e728ed](https://user-images.githubusercontent.com/109325265/207722747-2f2a2193-5e8f-45b9-9f19-ff40d73f643c.png)
![207705136-629cb68b-533b-4add-b2de-6cf46e6ffbf1](https://user-images.githubusercontent.com/109325265/207722749-eb908ce0-1fab-45c5-bea7-84e93da7290a.png)
![207705403-14c8e9e9-ea5e-4583-a667-48bc93fe1c26](https://user-images.githubusercontent.com/109325265/207722750-0cedfa79-f61f-45e2-9c51-e88823b55427.png)
![207704909-e1157baa-16fe-4d2e-8c52-2d17db713eba](https://user-images.githubusercontent.com/109325265/207722752-1d301a0a-eaeb-4627-a373-d77ba5420d7d.png)

 (server minecraft run on 192.168.0.215)
How can I do so that I can log in to the server with the proxy-protocol in nginx option?

**Comment by kzemek** [comment]
I don't believe nginx supports sending PROXY protocol.
