### ISSUE TITLE
do not support ipv6

### ISSUE THREAD

**Issue by heygo1345678** [path-network/go-mmproxy#21]
i try it (https://hub.docker.com/r/unixfox/go-mmproxy) but do not support ipv6
my nginx config:

map $ssl_preread_server_name $dot_map {

alist.example.com dot;
}

upstream dot{

    server 192.168.1.2:25577;
}
server {
listen 853 ;
listen [::]:853 ;
proxy_pass $dot_map;
ssl_preread on;

proxy_protocol on;

}

my docker go-mmproxy config :

#!/bin/sh
sleep 5
ip rule add from 127.0.0.1/8 iif lo table 123
ip route add local 0.0.0.0/0 dev lo table 123

ip -6 rule add from ::1/128 iif lo table 123
ip -6 route add local ::/0 dev lo table 123

echo -en "0.0.0.0/0\n::/0\n" > allowed-networks.txt
/usr/bin/go-mmproxy -l 0.0.0.0:25577 -4 127.0.0.1:853 -6 [::1]:853 --allowed-subnets allowed-networks.txt -v 2
/bin/sh

my adguard home listen 853 for dot
i checked adguard home it worked for ipv4 only, only have client real ip for ipv4
adguard home version v0.108.0-b.29
go-mmproxy log:
![tempsnip](https://user-images.githubusercontent.com/79509309/224250325-29863896-5b64-440d-9b5a-c03ab2484611.png)

**Comment by kzemek** [comment]
Hi @heygo1345678 , I can't reproduce the issue and have verified go-mmproxy does work with IPv6 both on the frontend side and the backend side. Please provide more details if you're still seeing an issue.
