### ISSUE TITLE
listen address is malformed

### ISSUE THREAD

**Issue by jinnatar** [path-network/go-mmproxy#27]
Trying to launch without any flags:
```json
{"time":"2023-11-07T16:57:22.637180523Z","level":"ERROR","msg":"listen address is malformed","error":"ParseAddr(\"0.0.0.0:8443\"): unexpected character (at \":8443\")"}
```

Manually specifying the default value results in the same. The parser seems to accept `0.0.0.0` but then obviously the port cannot be set. There doesn't seem to be a port flag.

**Comment by kzemek** [comment]
Thanks @Artanicus , this is now fixed.
