### ISSUE TITLE
netip address check disrupted the support for hostname-form address parameter

### ISSUE THREAD

**Issue by taleintervenor** [path-network/go-mmproxy#28]
The old version (go-mmproxy@v0.0.0-20220805111550-7197f99c984e) we used before support systemd service wrapper like:
```
[Unit]
Description=mmproxy golang implement from https://github.com/path-network/go-mmproxy
...

[Service]
Type=simple
ExecStart=/opt/go/bin/go-mmproxy -l %H:2222 -4 127.0.0.1:22 --allowed-subnets /etc/ssh/allowed-networks.txt -v 2
...
```
The **%H** in service wrapper will be translated to node hostname. But with latest version, go mmproxy will fail the netip check, so failed to start.

The necessity of using hostname instead of ip number is: there may be lots of backend nodes. If using ip address directly, we have to write different exec commands for each backend. Where as using %H macro we can keep an unified exec-cmd on all backends (we have private dns to resolve backends' hostname to their internal net ip).

So this may be a bad idea to add address format check if it not support dns resolve.

**Comment by kzemek** [comment]
Sorry, didn't mean to close the issue on this repo. Nevertheless it's fixed in https://github.com/kzemek/go-mmproxy main branch
