### ISSUE TITLE
crashes after start: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by onlyjob** [path-network/go-mmproxy#3]
`go-mmproxy` was working well for some time but now it fails as follows just a second after starting:

```
Apr 15 12:29:37 systemd[1]: Started go-mmproxy.
Apr 15 12:29:38 go-mmproxy[95866]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 15 12:29:38 go-mmproxy[95866]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x683157]
Apr 15 12:29:38 go-mmproxy[95866]: goroutine 7 [running]:
Apr 15 12:29:38 go-mmproxy[95866]: main.tcpHandleConnection(0x7962e0, 0xc000010050, 0xc000014780)
Apr 15 12:29:38 go-mmproxy[95866]:         github.com/path-network/go-mmproxy/tcp.go:58 +0xba7
Apr 15 12:29:38 go-mmproxy[95866]: created by main.TCPListen
Apr 15 12:29:38 go-mmproxy[95866]:         github.com/path-network/go-mmproxy/tcp.go:134 +0x371
```
Started with the following arguments:

    -4 127.0.0.1:22 -6 "[::1]:22" -allowed-subnets /etc/go-mmproxy/path-prefixes.txt -l 0.0.0.0:2222

Kernel is `5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux`. 

Please advise.

**Comment by kzemek** [comment]
Are you using go-mmproxy downloaded from the releases page, or built from source? If built from source, what version of Go are you using, and what's the Zap library version you built the executable with (e.g. `git -C ~/go/src/go.uber.org/zap rev-parse --short HEAD`)?

**Comment by onlyjob** [comment]
Built from source with Golang 1.13 and 1.14 (no difference). Initially I built "go-mmproxy" with "zap" v1.9.1 (from Debian package) but upgrading it to v1.14.1 did not help.

**Comment by kzemek** [comment]
Can you give me some more detail about your environment? What version of Debian are you running and is it fully updated? This might help me reproduce the issue.

Also, can you please paste the output when the panic happens while go-mmproxy is started with `-v 2` argument?

**Comment by kzemek** [comment]
Commit https://github.com/path-network/go-mmproxy/commit/cd9f1fb67f7af394c76fe3622a235cc53ebaac6b might fix the issue - it ensures that source address variable is not dereferenced for logging if it's nil. Note that the only case the source address might be nil is when go-mmproxy received a connection with `PROXY UNKNOWN` header.

**Comment by onlyjob** [comment]
Commit cd9f1fb fixed the problem! Thank you.

Maybe this problem happened due to _haproxy_ upgrade from 1.x to v2.0?
Also I'm forwarding connection with `send-proxy-v2`...

IMHO this (and other) commits since 1.0 warrant a new release.

FYI [go-mmproxy is in Debian](https://tracker.debian.org/pkg/go-mmproxy) :)

My environment is Debain 10 "Buster". Do you still want panic output with `-v 2`?

**Comment by kzemek** [comment]
I agree about the need for a new release. We'll be doing that soon :)
