### ISSUE TITLE
go-mmproxy not working for tcp4

### ISSUE THREAD

**Issue by shrey2682** [path-network/go-mmproxy#9]
I followed the steps mentioned [here](https://github.com/path-network/go-mmproxy) and successfully built go-mmproxy. However, after running the below command the application only opens port for tcp6 and not tcp:

******************************************************************************************
ubuntu@ip-10-10-10-204:~$ sudo ./go-mmproxy -l 0.0.0.0:2222 -4 127.0.0.1:2022 --allowed-subnets path-prefixes.txt
{"level":"info","ts":1625846200.1930776,"caller":"go-mmproxy@v0.0.0-20210226141941-e6156cbc7991/main.go:90","msg":"allowed subnet","subnet":"0.0.0.0/0"}
{"level":"info","ts":1625846200.1934776,"caller":"go-mmproxy@v0.0.0-20210226141941-e6156cbc7991/tcp.go:132","msg":"listening","listenerNum":0,"protocol":"tcp","listenAdr":"0.0.0.0:2222"}

******************************************************************************************
ubuntu@ip-10-10-10-204:/$ netstat -nta | grep 2222
tcp6       0      0 :::2222                 :::*                    LISTEN 
ubuntu@ip-10-10-10-204:/$
******************************************************************************************

Any idea about why is it not listening on 0.0.0.0:2222? Am I missing anything here?

**Comment by FreZZZeR** [comment]
Hello! I think it is no go-mmproxy problem.
It is correct application behavior when ipv6 is enabled in OS.
As default listening on 0.0.0.0 means listen ipv6 and ipv4 together.

You can check default behavior:
`cat /proc/sys/net/ipv6/bindv6only`
https://datatracker.ietf.org/doc/html/rfc3493#page-22
